{{/*
This file used for including source resources for RHDH and Sonataflow components from RC builds.
It requires including a secret to enable access to the image registries that contains the builds.
See https://github.com/janus-idp/operator/blob/main/.rhdh/docs/installing-ci-builds.adoc
*/}}

{{- $version := "" }}
{{- if or .Values.sonataFlowOperator.isReleaseCandidate .Values.rhdhOperator.isReleaseCandidate }}
  {{- $version = include "get-cluster-version" . -}}
{{- end}}

{{- if .Values.sonataFlowOperator.isReleaseCandidate }}
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  labels:
    operators.openshift.org/catalog: "true"
  name: brew-registry
spec:
  repositoryDigestMirrors:
    - mirrors:
        - brew.registry.redhat.io/openshift-serverless-1/logic-rhel8-operator
      source: registry.redhat.io/openshift-serverless-1/logic-rhel8-operator
    - mirrors:
        - brew.registry.redhat.io/rh-osbs/openshift-serverless-1-logic-operator-bundle
      source: registry-proxy.engineering.redhat.com/rh-osbs/openshift-serverless-1-logic-operator-bundle
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.sonataFlowOperator.subscription.sourceName }}
  namespace: openshift-marketplace
spec:
  displayName: Sonataflow Operator (Brew)
  image: {{ (get .Values.sonataflow.images $version) }}
  sourceType: grpc
  publisher: Sonataflow Operator (Brew)
---
{{- end}}

{{- if .Values.rhdhOperator.isReleaseCandidate }}
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: quay-io
spec:
  repositoryDigestMirrors:
  - mirrors:
    - quay.io/rhdh/rhdh-operator-bundle
    source: registry.redhat.io/rhdh/rhdh-operator-bundle
  - mirrors:
    - quay.io/rhdh/rhdh-operator-bundle
    source: registry.stage.redhat.io/rhdh/rhdh-operator-bundle
  - mirrors:
    - quay.io/rhdh/rhdh-operator-bundle
    source: registry-proxy.engineering.redhat.com/rh-osbs/rhdh-rhdh-operator-bundle
  - mirrors:
    - quay.io/rhdh/rhdh-rhel9-operator
    source: registry.redhat.io/rhdh/rhdh-rhel9-operator
  - mirrors:
    - quay.io/rhdh/rhdh-rhel9-operator
    source: registry.stage.redhat.io/rhdh/rhdh-rhel9-operator
  - mirrors:
    - quay.io/rhdh/rhdh-rhel9-operator
    source: registry-proxy.engineering.redhat.com/rh-osbs/rhdh-rhdh-rhel9-operator
  - mirrors:
    - quay.io/rhdh/rhdh-hub-rhel9
    source: registry.redhat.io/rhdh/rhdh-hub-rhel9
  - mirrors:
    - quay.io/rhdh/rhdh-hub-rhel9
    source: registry.stage.redhat.io/rhdh/rhdh-hub-rhel9
  - mirrors:
    - quay.io/rhdh/rhdh-hub-rhel9
    source: registry-proxy.engineering.redhat.com/rh-osbs/rhdh-rhdh-hub-rhel9
  - mirrors:
    - quay.io
    source: registry.redhat.io
  - mirrors:
    - quay.io
    source: registry.stage.redhat.io
  - mirrors:
    - quay.io
    source: registry-proxy.engineering.redhat.com
  - mirrors:
    - registry.redhat.io
    source: registry.stage.redhat.io
  - mirrors:
    - registry.stage.redhat.io
    source: registry-proxy.engineering.redhat.com
  - mirrors:
    - registry.redhat.io
    source: registry-proxy.engineering.redhat.com
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.rhdhOperator.subscription.sourceName }}
  namespace: openshift-marketplace
spec:
  displayName: IIB testing catalog
  image: {{ (get .Values.rhdh.images $version) }}
  sourceType: grpc
  publisher: IIB testing catalog
{{- end }}
