apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guest
  description: Team A
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
  memberOf: [guest]
