backstage:
  global:
    # added value when using with kubernetes tag
    host: localhost
    dynamic:
      includes:
        - dynamic-plugins.default.yaml
      plugins:
        - disabled: false
          integrity: >-
            sha512-kDbhP8Cq3PJFLJ6bwTRJwllxU71bnH7SkC3I3HqX6K9TVIqSKwyI8MNGYMRHoTlxwHH+4fASmFBPfEtIpMVLTA==
          package: "@janus-idp/backstage-plugin-orchestrator-backend-dynamic@1.3.1"
          pluginConfig:
            orchestrator:
              dataIndexService:
                url: http://sonataflow-platform-data-index-service.sonataflow-infra
              editor:
                path: "https://sandbox.kie.org/swf-chrome-extension/0.32.0"
        - disabled: false
          integrity: >-
            sha512-LeWPeeWChuscjJyAYla8R8hTj9sztfSRWyOZxP9akr8KRqkfI7CDFpvscpBT020k9AG6v5AfGn0job9DC9mFSg==
          package: "@janus-idp/backstage-plugin-orchestrator@1.4.3"
          pluginConfig:
            dynamicPlugins:
              frontend:
                janus-idp.backstage-plugin-orchestrator:
                  appIcons:
                    - importName: OrchestratorIcon
                      module: OrchestratorPlugin
                      name: orchestratorIcon
                  dynamicRoutes:
                    - importName: OrchestratorPage
                      menuItem:
                        icon: orchestratorIcon
                        text: Orchestrator
                      module: OrchestratorPlugin
                      path: /orchestrator
        - disabled: false
          package: "@janus-idp/plugin-notifications@1.1.6"
          integrity: >-
            sha512-wt0rn8O03Y/KpmQKbZ3JRkawhTgmSLlVUDm/k3zBsNdBZc5yBTQggC2ohJ1gTYirduMsuZ8FH1ftunjN5Mb/Hw==
          pluginConfig:
            dynamicPlugins:
              frontend:
                janus-idp.backstage-plugin-notifications:
                  appIcons:
                    - name: notificationsIcon
                      module: NotificationsPlugin
                      importName: NotificationsActiveIcon
                  dynamicRoutes:
                    - path: /notifications
                      importName: NotificationsPage
                      module: NotificationsPlugin
                      menuItem:
                        icon: notificationsIcon
                        text: Notifications
                      config:
                        pollingIntervalMs: 5000
        - disabled: false
          package: "@janus-idp/plugin-notifications-backend-dynamic@1.2.0"
          integrity: >-
            sha512-CHFRYd4Jm6Lsn5iNglejFx+aMgH3yYZDGJk7lMBRBjTpOuFzZk/4Qw4kTvC2arVbRnopDmaDrj3zPKGy5KWNRg==
  upstream:
    backstage:
      image:
        tag: next
      appConfig:
        integrations:
          github:
            - host: github.com
              token: "INSERT VALID TOKEN HERE"
        auth:
          environment: development
          providers:
            github:
              development:
                clientId: "INSERT VALID CLIENT ID HERE"
                clientSecret: "INSERT VALID CLIENT SECRET HERE"
        catalog:
          rules:
            - allow:
                [
                  Component,
                  System,
                  Group,
                  Resource,
                  Location,
                  Template,
                  API,
                  User,
                  Domain,
                ]
          locations:
            - type: url
              target: https://github.com/janus-idp/backstage-plugins/blob/main/plugins/notifications-backend/users.yaml
            - type: url
              target: https://github.com/parodos-dev/workflow-software-templates/blob/main/entities/workflow-resources.yaml
            - type: url
              target: https://github.com/parodos-dev/workflow-software-templates/blob/main/scaffolder-templates/basic-workflow/template.yaml
            - type: url
              target: https://github.com/parodos-dev/workflow-software-templates/blob/main/scaffolder-templates/complex-assessment-workflow/template.yaml
            - type: url
              target: https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml
        backend:
          csp:
            frame-src:
              - "https://sandbox.kie.org"
          database:
            client: pg
            connection:
              password: ${POSTGRESQL_ADMIN_PASSWORD}
              user: postgres
              host: orchestrator-postgresql-hl.orchestrator.svc.cluster.local
              port: 5432
