{{- $operatorGroupExists := include "operator-group-exists" (list .Values.subscription.namespace) }}
{{- if eq $operatorGroupExists "false" }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sonataflow-operator-group
  namespace: {{ .Values.subscription.namespace }}
spec: {}
---
{{- end }}
{{- if ne .Values.subscription.sourceImage "" }}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.subscription.source }}
  namespace: openshift-marketplace
spec:
  displayName: SonataFlow Operator (Development)
  image: {{ .Values.subscription.sourceImage }}
  sourceType: grpc
{{- end }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sonataflow-operator
  namespace: {{ .Values.subscription.namespace }}
spec:
  channel: {{ .Values.subscription.channel }}
  installPlanApproval: Automatic
  name: {{ .Values.subscription.pkgName }}
  source: {{ .Values.subscription.source | default (include "get-default-catalogsource-name" .) | quote }}
  sourceNamespace: {{ .Values.subscription.sourceNamespace | default (include "get-default-catalogsource-namespace" .) | quote }}
